/* Company financials — the INPUTS. No scores here; every score is computed
 * by score.js from these numbers. Figures are illustrative, shaped to resemble
 * what a 10-K discloses; the companies are fictional. */

export const COMPANIES = [
  { name:'Helios Cloud Systems', ticker:'NASDAQ: HLOS', sector:'Enterprise SaaS',
    revenueMillions:1840, revenueGrowth:34, netRetention:121, backlogGrowth:29,
    grossMargin:78, operatingMargin:12, fcfMargin:18,
    sgaPctRevenue:38, sgaGrowth:28, adSpendGrowth:31, techSpendPctRevenue:11,
    debtToEbitda:1.1, interestCoverage:14, currentRatio:2.4, cashRunwayMonths:60,
    riskFactorCount:28, customerConcentration:31, goingConcern:false,
    materialWeakness:false, litigationMaterial:false },

  { name:'Cobalt Semiconductors', ticker:'NASDAQ: CBLT', sector:'Semiconductors',
    revenueMillions:3120, revenueGrowth:27, netRetention:108, backlogGrowth:41,
    grossMargin:54, operatingMargin:24, fcfMargin:19,
    sgaPctRevenue:16, sgaGrowth:12, adSpendGrowth:9, techSpendPctRevenue:9,
    debtToEbitda:1.4, interestCoverage:18, currentRatio:2.9, cashRunwayMonths:72,
    riskFactorCount:31, customerConcentration:24, goingConcern:false,
    materialWeakness:false, litigationMaterial:false },

  { name:'Northbridge Financial', ticker:'NYSE: NBF', sector:'Fintech',
    revenueMillions:2650, revenueGrowth:18, netRetention:112, backlogGrowth:14,
    grossMargin:62, operatingMargin:21, fcfMargin:15,
    sgaPctRevenue:29, sgaGrowth:17, adSpendGrowth:23, techSpendPctRevenue:8,
    debtToEbitda:2.1, interestCoverage:9, currentRatio:1.8, cashRunwayMonths:44,
    riskFactorCount:43, customerConcentration:12, goingConcern:false,
    materialWeakness:false, litigationMaterial:true },

  { name:'Pinnacle Health Devices', ticker:'NASDAQ: PNHD', sector:'MedTech',
    revenueMillions:1180, revenueGrowth:15, netRetention:106, backlogGrowth:11,
    grossMargin:66, operatingMargin:14, fcfMargin:11,
    sgaPctRevenue:31, sgaGrowth:14, adSpendGrowth:16, techSpendPctRevenue:6,
    debtToEbitda:2.3, interestCoverage:7, currentRatio:2.1, cashRunwayMonths:38,
    riskFactorCount:36, customerConcentration:18, goingConcern:false,
    materialWeakness:false, litigationMaterial:false },

  { name:'Meridian Retail Group', ticker:'NYSE: MRG', sector:'Omnichannel Retail',
    revenueMillions:8900, revenueGrowth:6, netRetention:97, backlogGrowth:2,
    grossMargin:34, operatingMargin:6, fcfMargin:4,
    sgaPctRevenue:27, sgaGrowth:19, adSpendGrowth:22, techSpendPctRevenue:3,
    debtToEbitda:3.2, interestCoverage:4, currentRatio:1.3, cashRunwayMonths:26,
    riskFactorCount:39, customerConcentration:8, goingConcern:false,
    materialWeakness:false, litigationMaterial:false },

  { name:'Continental Freight Co.', ticker:'NYSE: CFRT', sector:'Logistics',
    revenueMillions:5400, revenueGrowth:3, netRetention:99, backlogGrowth:-2,
    grossMargin:28, operatingMargin:9, fcfMargin:8,
    sgaPctRevenue:14, sgaGrowth:4, adSpendGrowth:2, techSpendPctRevenue:2,
    debtToEbitda:2.6, interestCoverage:6, currentRatio:1.6, cashRunwayMonths:34,
    riskFactorCount:34, customerConcentration:21, goingConcern:false,
    materialWeakness:false, litigationMaterial:false },

  { name:'Vantage Media Holdings', ticker:'NASDAQ: VMH', sector:'Media',
    revenueMillions:2200, revenueGrowth:-4, netRetention:91, backlogGrowth:-11,
    grossMargin:41, operatingMargin:2, fcfMargin:-3,
    sgaPctRevenue:33, sgaGrowth:21, adSpendGrowth:26, techSpendPctRevenue:4,
    debtToEbitda:4.1, interestCoverage:2.2, currentRatio:1.1, cashRunwayMonths:20,
    riskFactorCount:47, customerConcentration:16, goingConcern:false,
    materialWeakness:true, litigationMaterial:true },

  { name:'Solstice Energy', ticker:'NYSE: SLST', sector:'Energy',
    revenueMillions:6800, revenueGrowth:-9, netRetention:94, backlogGrowth:-6,
    grossMargin:22, operatingMargin:5, fcfMargin:2,
    sgaPctRevenue:9, sgaGrowth:-7, adSpendGrowth:-12, techSpendPctRevenue:2,
    debtToEbitda:4.6, interestCoverage:2.8, currentRatio:1.2, cashRunwayMonths:22,
    riskFactorCount:58, customerConcentration:14, goingConcern:false,
    materialWeakness:false, litigationMaterial:true },

  { name:'Aster Biopharma', ticker:'NASDAQ: ASTB', sector:'Biotech',
    revenueMillions:95, revenueGrowth:41, netRetention:100, backlogGrowth:18,
    grossMargin:71, operatingMargin:-48, fcfMargin:-52,
    sgaPctRevenue:44, sgaGrowth:9, adSpendGrowth:3, techSpendPctRevenue:7,
    debtToEbitda:5.8, interestCoverage:0.4, currentRatio:2.2, cashRunwayMonths:17,
    riskFactorCount:62, customerConcentration:44, goingConcern:true,
    materialWeakness:false, litigationMaterial:false },

  { name:'Harbor Point Hospitality', ticker:'NYSE: HRBP', sector:'Hospitality',
    revenueMillions:1450, revenueGrowth:-2, netRetention:88, backlogGrowth:-8,
    grossMargin:26, operatingMargin:-3, fcfMargin:-6,
    sgaPctRevenue:21, sgaGrowth:11, adSpendGrowth:18, techSpendPctRevenue:2,
    debtToEbitda:5.4, interestCoverage:1.3, currentRatio:0.8, cashRunwayMonths:11,
    riskFactorCount:51, customerConcentration:9, goingConcern:true,
    materialWeakness:true, litigationMaterial:true },
];
